=== phac-nml/metadatatransformation/assets/schema_input.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/phac-nml/metadatatransformation/main/assets/schema_input.json",
    "title": "phac-nml/metadatatransformation pipeline - params.input schema",
    "description": "Schema for the file provided with params.input",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "sample": {
                "type": "string",
                "pattern": "^\\S+$",
                "meta": ["irida_id"],
                "errorMessage": "Sample name must be provided and cannot contain spaces."
            },
            "sample_name": {
                "type": "string",
                "meta": ["id"],
                "errorMessage": "Sample name is optional, if provided will replace sample for filenames and outputs"
            },
            "metadata_1": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_1"],
                "errorMessage": "Metadata associated with the sample (metadata_1).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_2": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_2"],
                "errorMessage": "Metadata associated with the sample (metadata_2).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_3": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_3"],
                "errorMessage": "Metadata associated with the sample (metadata_3).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_4": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_4"],
                "errorMessage": "Metadata associated with the sample (metadata_4).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_5": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_5"],
                "errorMessage": "Metadata associated with the sample (metadata_5).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_6": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_6"],
                "errorMessage": "Metadata associated with the sample (metadata_6).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_7": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_7"],
                "errorMessage": "Metadata associated with the sample (metadata_7).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_8": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_8"],
                "errorMessage": "Metadata associated with the sample (metadata_8).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_9": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_9"],
                "errorMessage": "Metadata associated with the sample (metadata_9).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_10": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_10"],
                "errorMessage": "Metadata associated with the sample (metadata_10).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_11": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_11"],
                "errorMessage": "Metadata associated with the sample (metadata_11).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_12": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_12"],
                "errorMessage": "Metadata associated with the sample (metadata_12).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_13": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_13"],
                "errorMessage": "Metadata associated with the sample (metadata_13).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_14": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_14"],
                "errorMessage": "Metadata associated with the sample (metadata_14).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_15": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_15"],
                "errorMessage": "Metadata associated with the sample (metadata_15).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_16": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_16"],
                "errorMessage": "Metadata associated with the sample (metadata_16).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            }
        },
        "required": ["sample"]
    },
    "uniqueEntries": ["sample"]
}

=== phac-nml/metadatatransformation/tests/data/samplesheets/earliest/basic.json
[
  {
    "sample": "sample1",
    "sample_name": "ABC",
    "metadata_1": "2000-01-01",
    "metadata_2": "2000-01-02",
    "metadata_3": "2000-01-03",
    "metadata_4": "2000-01-04",
    "metadata_5": "2000-01-05",
    "metadata_6": "2000-01-06",
    "metadata_7": "2000-01-07",
    "metadata_8": "2000-01-08"
  },
  {
    "sample": "sample2",
    "sample_name": "DEF",
    "metadata_1": "2000-02-01",
    "metadata_2": "2000-02-02",
    "metadata_3": "2000-02-03",
    "metadata_4": "2000-02-04",
    "metadata_5": "2000-02-05",
    "metadata_6": "2000-02-06",
    "metadata_7": "2000-02-07",
    "metadata_8": "2000-02-08"
  },
  {
    "sample": "sample3",
    "sample_name": "GHI",
    "metadata_1": "2000-03-01",
    "metadata_2": "2000-03-02",
    "metadata_3": "2000-03-03",
    "metadata_4": "2000-03-04",
    "metadata_5": "2000-03-05",
    "metadata_6": "2000-03-06",
    "metadata_7": "2000-03-07",
    "metadata_8": "2000-03-08"
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/age/problems.json
[
  {
    "sample": "reverse_dates_under_2",
    "sample_name": "rd_1",
    "metadata_1": "2001-01-01",
    "metadata_2": "2000-01-01"
  },
  {
    "sample": "reverse_dates_over_2",
    "sample_name": "rd_2",
    "metadata_1": "2010-01-01",
    "metadata_2": "2000-01-01"
  },
  {
    "sample": "bad_format_1",
    "sample_name": "bf_1",
    "metadata_1": "00-01-01",
    "metadata_2": "2000-11-11"
  },
  {
    "sample": "bad_format_2",
    "sample_name": "bf_2",
    "metadata_1": "2000-01-01",
    "metadata_2": "00-11-11"
  },
  {
    "sample": "bad_format_3",
    "sample_name": "bf_3",
    "metadata_1": "2000/01/01",
    "metadata_2": "2000/11/11"
  },
  {
    "sample": "bad_format_4",
    "sample_name": "bf_4",
    "metadata_1": "2000.01.01",
    "metadata_2": "2000.11.11"
  },
  {
    "sample": "bad_format_5",
    "sample_name": "bf_5",
    "metadata_1": "2000-01-01",
    "metadata_2": "2000-11-11 23:59:59"
  },
  {
    "sample": "wrong_order_1",
    "sample_name": "wo_1",
    "metadata_1": "2000-31-01",
    "metadata_2": "2000-01-02"
  },
  {
    "sample": "wrong_order_2",
    "sample_name": "wo_2",
    "metadata_1": "2000-01-01",
    "metadata_2": "2000-31-02"
  },
  {
    "sample": "negative_date_1",
    "sample_name": "nd_1",
    "metadata_1": "-2000-01-01",
    "metadata_2": "2001-01-01"
  },
  {
    "sample": "negative_date_2",
    "sample_name": "nd_2",
    "metadata_1": "2000-01-01",
    "metadata_2": "-2001-01-01"
  },
  {
    "sample": "missing_date_1",
    "sample_name": "md_1",
    "metadata_1": "",
    "metadata_2": "2001-01-01"
  },
  {
    "sample": "missing_date_2",
    "sample_name": "md_2",
    "metadata_1": "2000-01-01",
    "metadata_2": ""
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/age_pnc/basic.json
[
    {
        "sample": "sample1",
        "sample_name": "1",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-02",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample2",
        "sample_name": "2",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-03",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample3",
        "sample_name": "3",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-04-01",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample4",
        "sample_name": "4",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-12-31",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample5",
        "sample_name": "5",
        "metadata_1": "2000-01-01",
        "metadata_2": "2001-04-01",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample6",
        "sample_name": "6",
        "metadata_1": "2000-01-01",
        "metadata_2": "2001-12-31",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample7",
        "sample_name": "7",
        "metadata_1": "2000-01-01",
        "metadata_2": "2002-01-01",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample8",
        "sample_name": "8",
        "metadata_1": "2000-02-29",
        "metadata_2": "2024-02-29",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample9",
        "sample_name": "9",
        "metadata_1": "1950-12-31",
        "metadata_2": "2000-05-05",
        "metadata_3": "",
        "metadata_4": ""
    },
    {
        "sample": "sample10",
        "sample_name": "10",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "1",
        "metadata_4": "day"
    },
    {
        "sample": "sample11",
        "sample_name": "11",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "2",
        "metadata_4": "days"
    },
    {
        "sample": "sample12",
        "sample_name": "12",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "3",
        "metadata_4": "days"
    },
    {
        "sample": "sample13",
        "sample_name": "13",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "365",
        "metadata_4": "days"
    },
    {
        "sample": "sample14",
        "sample_name": "14",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "729",
        "metadata_4": "days"
    },
    {
        "sample": "sample15",
        "sample_name": "15",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "730",
        "metadata_4": "days"
    },
    {
        "sample": "sample16",
        "sample_name": "16",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "731",
        "metadata_4": "days"
    },
    {
        "sample": "sample17",
        "sample_name": "17",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "1",
        "metadata_4": "week"
    },
    {
        "sample": "sample18",
        "sample_name": "18",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "2",
        "metadata_4": "weeks"
    },
    {
        "sample": "sample19",
        "sample_name": "19",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "52",
        "metadata_4": "weeks"
    },
    {
        "sample": "sample20",
        "sample_name": "20",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "104",
        "metadata_4": "weeks"
    },
    {
        "sample": "sample21",
        "sample_name": "21",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "1",
        "metadata_4": "month"
    },
    {
        "sample": "sample22",
        "sample_name": "22",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "2",
        "metadata_4": "months"
    },
    {
        "sample": "sample23",
        "sample_name": "23",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "12",
        "metadata_4": "months"
    },
    {
        "sample": "sample24",
        "sample_name": "24",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "24",
        "metadata_4": "months"
    },
    {
        "sample": "sample25",
        "sample_name": "25",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "1",
        "metadata_4": "year"
    },
    {
        "sample": "sample26",
        "sample_name": "26",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "2",
        "metadata_4": "years"
    },
    {
        "sample": "sample27",
        "sample_name": "27",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "3",
        "metadata_4": "years"
    },
    {
        "sample": "sample28",
        "sample_name": "28",
        "metadata_1": "2000-01-02",
        "metadata_2": "2000-01-02",
        "metadata_3": "1",
        "metadata_4": "day"
    },
    {
        "sample": "sample29",
        "sample_name": "29",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-12-31",
        "metadata_3": "366",
        "metadata_4": "day"
    }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/earliest/all_problems.json
[
  {
    "sample": "sample1",
    "sample_name": "ABC",
    "metadata_1": "a",
    "metadata_2": "a",
    "metadata_3": "a",
    "metadata_4": "a",
    "metadata_5": "a",
    "metadata_6": "a",
    "metadata_7": "a",
    "metadata_8": "a"
  },
  {
    "sample": "sample2",
    "sample_name": "DEF",
    "metadata_1": "b",
    "metadata_2": "b",
    "metadata_3": "b",
    "metadata_4": "b",
    "metadata_5": "b",
    "metadata_6": "b",
    "metadata_7": "b",
    "metadata_8": "b"
  },
  {
    "sample": "sample3",
    "sample_name": "GHI",
    "metadata_1": "c",
    "metadata_2": "c",
    "metadata_3": "c",
    "metadata_4": "c",
    "metadata_5": "c",
    "metadata_6": "c",
    "metadata_7": "c",
    "metadata_8": "c"
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/earliest/special.json
[
  {
    "sample": "sample1",
    "sample_name": "normal",
    "metadata_1": "2000-01-01",
    "metadata_2": "Not Applicable",
    "metadata_3": "Missing",
    "metadata_4": "Not Collected",
    "metadata_5": "Not Provided",
    "metadata_6": "Restricted Access",
    "metadata_7": "",
    "metadata_8": "2000-01-08"
  },
  {
    "sample": "sample2",
    "sample_name": "mixed_case",
    "metadata_1": "2000-02-01",
    "metadata_2": "not Applicable",
    "metadata_3": "MIssIng",
    "metadata_4": "not Collected",
    "metadata_5": "not Provided",
    "metadata_6": "restricted Access",
    "metadata_7": "",
    "metadata_8": "2000-02-08"
  },
  {
    "sample": "sample3",
    "sample_name": "lowercase",
    "metadata_1": "2000-03-01",
    "metadata_2": "not applicable",
    "metadata_3": "missing",
    "metadata_4": "not collected",
    "metadata_5": "not provided",
    "metadata_6": "restricted access",
    "metadata_7": "",
    "metadata_8": "2000-03-08"
  },
  {
    "sample": "sample4",
    "sample_name": "bad_data",
    "metadata_1": "2000-03-01",
    "metadata_2": "not applicable",
    "metadata_3": "BAD_DATA",
    "metadata_4": "not collected",
    "metadata_5": "not provided",
    "metadata_6": "restricted access",
    "metadata_7": "",
    "metadata_8": "2000-03-08"
  },
  {
    "sample": "sample5",
    "sample_name": "bad_date_format",
    "metadata_1": "2000-03-01",
    "metadata_2": "not applicable",
    "metadata_3": "2000-20-01",
    "metadata_4": "not collected",
    "metadata_5": "not provided",
    "metadata_6": "restricted access",
    "metadata_7": "",
    "metadata_8": "2000-03-08"
  },
  {
    "sample": "sample6",
    "sample_name": "all_special",
    "metadata_1": "not applicable",
    "metadata_2": "not applicable",
    "metadata_3": "missing",
    "metadata_4": "not collected",
    "metadata_5": "not provided",
    "metadata_6": "restricted access",
    "metadata_7": "not applicable",
    "metadata_8": "not applicable"
  },
  {
    "sample": "sample7",
    "sample_name": "all_special_and_blank",
    "metadata_1": "",
    "metadata_2": "not applicable",
    "metadata_3": "missing",
    "metadata_4": "not collected",
    "metadata_5": "not provided",
    "metadata_6": "restricted access",
    "metadata_7": "",
    "metadata_8": ""
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/pnc/column_order.json
[
    {
        "sample": "sample1",
        "sample_name": "basic1",
        "metadata_1": "10",
        "metadata_2": "year",
        "metadata_3": "2010-01-01",
        "metadata_4": "Homo sapiens (Human)",
        "metadata_5": "Human NCBITaxon:9606",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": "",
        "metadata_9": "2020-01-01",
        "metadata_10": "2020-01-02",
        "metadata_11": "2020-01-03",
        "metadata_12": "2020-01-04",
        "metadata_13": "2020-01-05",
        "metadata_14": "2020-01-06"
    }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/age/extra_columns.json
[
  {
    "sample": "sample1",
    "sample_name": "ABC",
    "metadata_1": "2000-01-01",
    "metadata_2": "2000-12-31",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": "",
    "metadata_6": "",
    "metadata_7": "",
    "metadata_8": ""
  },
  {
    "sample": "sample2",
    "sample_name": "DEF",
    "metadata_1": "2000-02-29",
    "metadata_2": "2024-02-29",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": "",
    "metadata_6": "",
    "metadata_7": "",
    "metadata_8": ""
  },
  {
    "sample": "sample3",
    "sample_name": "GHI",
    "metadata_1": "1950-12-31",
    "metadata_2": "2000-05-05",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": "",
    "metadata_6": "",
    "metadata_7": "",
    "metadata_8": ""
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/earliest/problems.json
[
    {
        "sample": "sample1",
        "sample_name": "normal",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-02",
        "metadata_3": "2000-01-03",
        "metadata_4": "2000-01-04",
        "metadata_5": "2000-01-05",
        "metadata_6": "2000-01-06",
        "metadata_7": "2000-01-07",
        "metadata_8": "2000-01-08"
    },
    {
        "sample": "sample2",
        "sample_name": "all_missing",
        "metadata_1": "",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": ""
    },
    {
        "sample": "sample3",
        "sample_name": "some_missing",
        "metadata_1": "",
        "metadata_2": "2000-03-02",
        "metadata_3": "",
        "metadata_4": "2000-03-04",
        "metadata_5": "",
        "metadata_6": "2000-03-06",
        "metadata_7": "",
        "metadata_8": "2000-03-08"
    },
    {
        "sample": "sample4",
        "sample_name": "only_non_strings",
        "metadata_1": "12",
        "metadata_2": "",
        "metadata_3": "a",
        "metadata_4": "",
        "metadata_5": "0.5",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": "1"
    },
    {
        "sample": "sample5",
        "sample_name": "only_bad_dates",
        "metadata_1": "2000-30-12",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": "2000-30-01"
    },
    {
        "sample": "sample6",
        "sample_name": "mix_good_bad_dates",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-02",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "2000-30-12",
        "metadata_8": "2000-30-01"
    },
    {
        "sample": "sample7",
        "sample_name": "mix_dates_non_dates",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-02",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "cat",
        "metadata_8": "0.5"
    },
    {
        "sample": "sample8",
        "sample_name": "only_one_integer",
        "metadata_1": "1",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": ""
    },
    {
        "sample": "sample9",
        "sample_name": "only_one_float",
        "metadata_1": "0.1",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": ""
    },
    {
        "sample": "sample10",
        "sample_name": "only_one_string",
        "metadata_1": "cat",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": ""
    },
    {
        "sample": "sample11",
        "sample_name": "only_one_char",
        "metadata_1": "a",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": ""
    },
    {
        "sample": "sample12",
        "sample_name": "only_one_date",
        "metadata_1": "2000-01-01",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": ""
    },
    {
        "sample": "sample13",
        "sample_name": "one_integer_one_date",
        "metadata_1": "1",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample14",
        "sample_name": "one_float_one_date",
        "metadata_1": "0.1",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample15",
        "sample_name": "one_string_one_date",
        "metadata_1": "cat",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample16",
        "sample_name": "one_char_one_date",
        "metadata_1": "a",
        "metadata_2": "",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "",
        "metadata_7": "",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample17",
        "sample_name": "many_integer_one_date",
        "metadata_1": "1",
        "metadata_2": "2",
        "metadata_3": "3",
        "metadata_4": "4",
        "metadata_5": "5",
        "metadata_6": "6",
        "metadata_7": "7",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample18",
        "sample_name": "many_float_one_date",
        "metadata_1": "0.1",
        "metadata_2": "0.2",
        "metadata_3": "0.3",
        "metadata_4": "0.4",
        "metadata_5": "0.5",
        "metadata_6": "0.6",
        "metadata_7": "0.7",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample19",
        "sample_name": "many_string_one_date",
        "metadata_1": "cat",
        "metadata_2": "dog",
        "metadata_3": "fish",
        "metadata_4": "hamster",
        "metadata_5": "rat",
        "metadata_6": "mouse",
        "metadata_7": "bird",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample20",
        "sample_name": "many_char_one_date",
        "metadata_1": "a",
        "metadata_2": "b",
        "metadata_3": "c",
        "metadata_4": "d",
        "metadata_5": "e",
        "metadata_6": "f",
        "metadata_7": "g",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample21",
        "sample_name": "one_integer_many_date",
        "metadata_1": "1",
        "metadata_2": "2000-01-01",
        "metadata_3": "2000-01-02",
        "metadata_4": "2000-01-03",
        "metadata_5": "2000-01-04",
        "metadata_6": "2000-01-05",
        "metadata_7": "2000-01-06",
        "metadata_8": "2000-01-07"
    },
    {
        "sample": "sample22",
        "sample_name": "one_float_many_date",
        "metadata_1": "0.1",
        "metadata_2": "2000-01-01",
        "metadata_3": "2000-01-02",
        "metadata_4": "2000-01-03",
        "metadata_5": "2000-01-04",
        "metadata_6": "2000-01-05",
        "metadata_7": "2000-01-06",
        "metadata_8": "2000-01-07"
    },
    {
        "sample": "sample23",
        "sample_name": "one_string_many_date",
        "metadata_1": "cat",
        "metadata_2": "2000-01-01",
        "metadata_3": "2000-01-02",
        "metadata_4": "2000-01-03",
        "metadata_5": "2000-01-04",
        "metadata_6": "2000-01-05",
        "metadata_7": "2000-01-06",
        "metadata_8": "2000-01-07"
    },
    {
        "sample": "sample24",
        "sample_name": "one_char_many_date",
        "metadata_1": "a",
        "metadata_2": "2000-01-01",
        "metadata_3": "2000-01-02",
        "metadata_4": "2000-01-03",
        "metadata_5": "2000-01-04",
        "metadata_6": "2000-01-05",
        "metadata_7": "2000-01-06",
        "metadata_8": "2000-01-07"
    },
    {
        "sample": "sample25",
        "sample_name": "duplicates",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-01",
        "metadata_3": "2000-01-01",
        "metadata_4": "2000-01-01",
        "metadata_5": "2000-01-01",
        "metadata_6": "2000-01-01",
        "metadata_7": "2000-01-01",
        "metadata_8": "2000-01-01"
    },
    {
        "sample": "sample26",
        "sample_name": "duplicates_missing",
        "metadata_1": "2000-01-01",
        "metadata_2": "",
        "metadata_3": "2000-01-01",
        "metadata_4": "",
        "metadata_5": "2000-01-01",
        "metadata_6": "",
        "metadata_7": "2000-01-01",
        "metadata_8": ""
    },
    {
        "sample": "sample27",
        "sample_name": "duplicates_mixed",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-01",
        "metadata_3": "2000-01-01",
        "metadata_4": "2000-01-01",
        "metadata_5": "2000-01-02",
        "metadata_6": "2000-01-02",
        "metadata_7": "2000-01-02",
        "metadata_8": "2000-01-02"
    }
]
