=== phac-nml/metadatatransformation/assets/schema_input.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/phac-nml/metadatatransformation/main/assets/schema_input.json",
    "title": "phac-nml/metadatatransformation pipeline - params.input schema",
    "description": "Schema for the file provided with params.input",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "sample": {
                "type": "string",
                "pattern": "^\\S+$",
                "meta": ["irida_id"],
                "errorMessage": "Sample name must be provided and cannot contain spaces."
            },
            "sample_name": {
                "type": "string",
                "meta": ["id"],
                "errorMessage": "Sample name is optional, if provided will replace sample for filenames and outputs"
            },
            "metadata_1": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_1"],
                "errorMessage": "Metadata associated with the sample (metadata_1).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_2": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_2"],
                "errorMessage": "Metadata associated with the sample (metadata_2).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_3": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_3"],
                "errorMessage": "Metadata associated with the sample (metadata_3).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_4": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_4"],
                "errorMessage": "Metadata associated with the sample (metadata_4).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_5": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_5"],
                "errorMessage": "Metadata associated with the sample (metadata_5).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_6": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_6"],
                "errorMessage": "Metadata associated with the sample (metadata_6).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_7": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_7"],
                "errorMessage": "Metadata associated with the sample (metadata_7).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_8": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_8"],
                "errorMessage": "Metadata associated with the sample (metadata_8).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_9": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_9"],
                "errorMessage": "Metadata associated with the sample (metadata_9).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_10": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_10"],
                "errorMessage": "Metadata associated with the sample (metadata_10).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_11": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_11"],
                "errorMessage": "Metadata associated with the sample (metadata_11).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_12": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_12"],
                "errorMessage": "Metadata associated with the sample (metadata_12).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_13": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_13"],
                "errorMessage": "Metadata associated with the sample (metadata_13).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_14": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_14"],
                "errorMessage": "Metadata associated with the sample (metadata_14).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_15": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_15"],
                "errorMessage": "Metadata associated with the sample (metadata_15).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_16": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_16"],
                "errorMessage": "Metadata associated with the sample (metadata_16).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            }
        },
        "required": ["sample"]
    },
    "uniqueEntries": ["sample"]
}

=== phac-nml/metadatatransformation/tests/data/samplesheets/categorize/basic.json
[
  {
    "sample": "sample1",
    "sample_name": "A",
    "metadata_1": "Homo sapiens (Human)",
    "metadata_2": "Human NCBITaxon:9606",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample2",
    "sample_name": "B",
    "metadata_1": "",
    "metadata_2": "dog",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample3",
    "sample_name": "C",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "eggs",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample4",
    "sample_name": "D",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "farm",
    "metadata_5": "wastewater"
  },
  {
    "sample": "sample5",
    "sample_name": "E",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample6",
    "sample_name": "F",
    "metadata_1": "Homo sapiens (Human)",
    "metadata_2": "dog",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample7",
    "sample_name": "G",
    "metadata_1": "Homo sapiens (Human)",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample8",
    "sample_name": "H",
    "metadata_1": "",
    "metadata_2": "Human NCBITaxon:9606",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample9",
    "sample_name": "J",
    "metadata_1": "Homo sapiens (Human)",
    "metadata_2": "Human NCBITaxon:9606",
    "metadata_3": "eggs",
    "metadata_4": "farm",
    "metadata_5": "wastewater"
  },
  {
    "sample": "sample10",
    "sample_name": "K",
    "metadata_1": "",
    "metadata_2": "dog",
    "metadata_3": "eggs",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample11",
    "sample_name": "L",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "eggs",
    "metadata_4": "farm",
    "metadata_5": ""
  },
  {
    "sample": "sample12",
    "sample_name": "M",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "eggs",
    "metadata_4": "",
    "metadata_5": "wastewater"
  }
]
