=== phac-nml/metadatatransformation/assets/schema_input.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/phac-nml/metadatatransformation/main/assets/schema_input.json",
    "title": "phac-nml/metadatatransformation pipeline - params.input schema",
    "description": "Schema for the file provided with params.input",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "sample": {
                "type": "string",
                "pattern": "^\\S+$",
                "meta": ["irida_id"],
                "errorMessage": "Sample name must be provided and cannot contain spaces."
            },
            "sample_name": {
                "type": "string",
                "meta": ["id"],
                "errorMessage": "Sample name is optional, if provided will replace sample for filenames and outputs"
            },
            "metadata_1": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_1"],
                "errorMessage": "Metadata associated with the sample (metadata_1).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_2": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_2"],
                "errorMessage": "Metadata associated with the sample (metadata_2).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_3": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_3"],
                "errorMessage": "Metadata associated with the sample (metadata_3).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_4": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_4"],
                "errorMessage": "Metadata associated with the sample (metadata_4).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_5": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_5"],
                "errorMessage": "Metadata associated with the sample (metadata_5).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_6": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_6"],
                "errorMessage": "Metadata associated with the sample (metadata_6).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_7": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_7"],
                "errorMessage": "Metadata associated with the sample (metadata_7).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_8": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_8"],
                "errorMessage": "Metadata associated with the sample (metadata_8).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_9": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_9"],
                "errorMessage": "Metadata associated with the sample (metadata_9).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_10": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_10"],
                "errorMessage": "Metadata associated with the sample (metadata_10).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_11": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_11"],
                "errorMessage": "Metadata associated with the sample (metadata_11).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_12": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_12"],
                "errorMessage": "Metadata associated with the sample (metadata_12).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_13": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_13"],
                "errorMessage": "Metadata associated with the sample (metadata_13).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_14": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_14"],
                "errorMessage": "Metadata associated with the sample (metadata_14).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_15": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_15"],
                "errorMessage": "Metadata associated with the sample (metadata_15).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            },
            "metadata_16": {
                "type": ["string", "number", "integer", "boolean"],
                "meta": ["metadata_16"],
                "errorMessage": "Metadata associated with the sample (metadata_16).",
                "default": "",
                "pattern": "^[^\\n\\t\"]+$"
            }
        },
        "required": ["sample"]
    },
    "uniqueEntries": ["sample"]
}

=== phac-nml/metadatatransformation/tests/data/samplesheets/age/basic.json
[
    {
        "sample": "sample1",
        "sample_name": "ABC",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-01"
    },
    {
        "sample": "sample2",
        "sample_name": "DEF",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-01-02"
    },
    {
        "sample": "sample3",
        "sample_name": "GHI",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-04-01"
    },
    {
        "sample": "sample4",
        "sample_name": "JKL",
        "metadata_1": "2000-01-01",
        "metadata_2": "2000-12-31"
    },
    {
        "sample": "sample5",
        "sample_name": "MNO",
        "metadata_1": "2000-01-01",
        "metadata_2": "2001-04-01"
    },
    {
        "sample": "sample6",
        "sample_name": "PQR",
        "metadata_1": "2000-01-01",
        "metadata_2": "2001-12-31"
    },
    {
        "sample": "sample7",
        "sample_name": "STU",
        "metadata_1": "2000-01-01",
        "metadata_2": "2002-01-01"
    },
    {
        "sample": "sample8",
        "sample_name": "VWX",
        "metadata_1": "2000-02-29",
        "metadata_2": "2024-02-29"
    },
    {
        "sample": "sample9",
        "sample_name": "YZ",
        "metadata_1": "1950-12-31",
        "metadata_2": "2000-05-05"
    }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/lock/missing_column.json
[
  {
    "sample": "sample1",
    "sample_name": "ABC",
    "metadata_1": "1.1",
    "metadata_2": "1.2",
    "metadata_3": "1.3",
    "metadata_4": "",
    "metadata_5": "1.5",
    "metadata_6": "1.6",
    "metadata_7": "1.7",
    "metadata_8": "1.8"
  },
  {
    "sample": "sample2",
    "sample_name": "DEF",
    "metadata_1": "2.1",
    "metadata_2": "2.2",
    "metadata_3": "2.3",
    "metadata_4": "",
    "metadata_5": "2.5",
    "metadata_6": "2.6",
    "metadata_7": "2.7",
    "metadata_8": "2.8"
  },
  {
    "sample": "sample3",
    "sample_name": "GHI",
    "metadata_1": "3.1",
    "metadata_2": "3.2",
    "metadata_3": "3.3",
    "metadata_4": "",
    "metadata_5": "3.5",
    "metadata_6": "3.6",
    "metadata_7": "3.7",
    "metadata_8": "3.8"
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/age_pnc/specification.json
[
    {
        "sample": "sample1",
        "sample_name": "1",
        "metadata_1": "2025-02-01",
        "metadata_2": "1",
        "metadata_3": "month",
        "metadata_4": "2025-01-01",
        "metadata_5": "0.083",
        "metadata_6": ""
    },
    {
        "sample": "sample2",
        "sample_name": "2",
        "metadata_1": "2025-04-11",
        "metadata_2": "90",
        "metadata_3": "day",
        "metadata_4": "2025-04-01",
        "metadata_5": "0.027",
        "metadata_6": "Mismatch between CALC_HOST_AGE and HOST_AGE"
    },
    {
        "sample": "sample3",
        "sample_name": "3",
        "metadata_1": "2025-08-11",
        "metadata_2": "40",
        "metadata_3": "year",
        "metadata_4": "1985-08-10",
        "metadata_5": "40",
        "metadata_6": ""
    },
    {
        "sample": "sample4",
        "sample_name": "4",
        "metadata_1": "2025-02-01",
        "metadata_2": "1",
        "metadata_3": "month",
        "metadata_4": "",
        "metadata_5": "0.083",
        "metadata_6": ""
    },
    {
        "sample": "sample5",
        "sample_name": "5",
        "metadata_1": "2025-04-11",
        "metadata_2": "90",
        "metadata_3": "day",
        "metadata_4": "",
        "metadata_5": "0.247",
        "metadata_6": ""
    },
    {
        "sample": "sample6",
        "sample_name": "6",
        "metadata_1": "2025-08-11",
        "metadata_2": "40",
        "metadata_3": "year",
        "metadata_4": "",
        "metadata_5": "40",
        "metadata_6": ""
    },
    {
        "sample": "sample7",
        "sample_name": "7",
        "metadata_1": "2025-02-01",
        "metadata_2": "1",
        "metadata_3": "month",
        "metadata_4": "Not Applicable",
        "metadata_5": "0.083",
        "metadata_6": ""
    },
    {
        "sample": "sample8",
        "sample_name": "8",
        "metadata_1": "2025-04-11",
        "metadata_2": "90",
        "metadata_3": "day",
        "metadata_4": "Missing",
        "metadata_5": "0.247",
        "metadata_6": ""
    },
    {
        "sample": "sample9",
        "sample_name": "9",
        "metadata_1": "2025-08-11",
        "metadata_2": "40",
        "metadata_3": "year",
        "metadata_4": "Not Collected",
        "metadata_5": "40",
        "metadata_6": ""
    },
    {
        "sample": "sample10",
        "sample_name": "10",
        "metadata_1": "2025-02-01",
        "metadata_2": "1",
        "metadata_3": "month",
        "metadata_4": "Not Provided",
        "metadata_5": "0.083",
        "metadata_6": ""
    },
    {
        "sample": "sample11",
        "sample_name": "11",
        "metadata_1": "2025-04-11",
        "metadata_2": "90",
        "metadata_3": "day",
        "metadata_4": "Restricted Access",
        "metadata_5": "0.247",
        "metadata_6": ""
    },
    {
        "sample": "sample12",
        "sample_name": "12",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "10",
        "metadata_6": ""
    },
    {
        "sample": "sample13",
        "sample_name": "13",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "cycles",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "Invalid HOST_AGE_UNIT"
    },
    {
        "sample": "sample14",
        "sample_name": "14",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "units",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "Invalid HOST_AGE_UNIT"
    },
    {
        "sample": "sample15",
        "sample_name": "15",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "Restricted Access",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "Invalid HOST_AGE_UNIT"
    },
    {
        "sample": "sample16",
        "sample_name": "16",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "",
        "metadata_4": "2025-01-01",
        "metadata_5": "",
        "metadata_6": "EARLIEST DATE MISSING"
    },
    {
        "sample": "sample17",
        "sample_name": "17",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "cycles",
        "metadata_4": "2025-01-01",
        "metadata_5": "",
        "metadata_6": "Invalid HOST_AGE_UNIT; EARLIEST DATE MISSING"
    },
    {
        "sample": "sample18",
        "sample_name": "18",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "units",
        "metadata_4": "2025-01-01",
        "metadata_5": "",
        "metadata_6": "Invalid HOST_AGE_UNIT; EARLIEST DATE MISSING"
    },
    {
        "sample": "sample19",
        "sample_name": "19",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "bananas",
        "metadata_4": "2025-01-01",
        "metadata_5": "",
        "metadata_6": "Invalid HOST_AGE_UNIT; EARLIEST DATE MISSING"
    },
    {
        "sample": "sample20",
        "sample_name": "20",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "Not Applicable",
        "metadata_4": "",
        "metadata_5": "10",
        "metadata_6": ""
    },
    {
        "sample": "sample21",
        "sample_name": "21",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "Missing",
        "metadata_4": "",
        "metadata_5": "10",
        "metadata_6": ""
    },
    {
        "sample": "sample22",
        "sample_name": "22",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "Not Collected",
        "metadata_4": "",
        "metadata_5": "10",
        "metadata_6": ""
    },
    {
        "sample": "sample23",
        "sample_name": "23",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "Not Provided",
        "metadata_4": "",
        "metadata_5": "10",
        "metadata_6": ""
    },
    {
        "sample": "sample24",
        "sample_name": "24",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "Restricted Access",
        "metadata_4": "",
        "metadata_5": "10",
        "metadata_6": ""
    },
    {
        "sample": "sample25",
        "sample_name": "25",
        "metadata_1": "",
        "metadata_2": "10",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": ""
    },
    {
        "sample": "sample26",
        "sample_name": "26",
        "metadata_1": "2020-01-12",
        "metadata_2": "-1",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "negative value; Invalid HOST_AGE_UNIT"
    },
    {
        "sample": "sample27",
        "sample_name": "27",
        "metadata_1": "1998-06-15",
        "metadata_2": "500",
        "metadata_3": "year",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "age is not reasonable"
    },
    {
        "sample": "sample28",
        "sample_name": "28",
        "metadata_1": "1900-01-01",
        "metadata_2": "500",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "age is not reasonable; Invalid HOST_AGE_UNIT"
    },
    {
        "sample": "sample29",
        "sample_name": "29",
        "metadata_1": "",
        "metadata_2": "150",
        "metadata_3": "year",
        "metadata_4": "",
        "metadata_5": "150",
        "metadata_6": ""
    },
    {
        "sample": "sample30",
        "sample_name": "30",
        "metadata_1": "",
        "metadata_2": "fledgling",
        "metadata_3": "year",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "invalid host age"
    },
    {
        "sample": "sample31",
        "sample_name": "31",
        "metadata_1": "2019-12-22",
        "metadata_2": "1/2",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "invalid host age"
    },
    {
        "sample": "sample32",
        "sample_name": "32",
        "metadata_1": "2017-06-14",
        "metadata_2": "0",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "invalid host age"
    },
    {
        "sample": "sample33",
        "sample_name": "33",
        "metadata_1": "2019-07-12",
        "metadata_2": "5",
        "metadata_3": "week",
        "metadata_4": "",
        "metadata_5": "0.096",
        "metadata_6": ""
    },
    {
        "sample": "sample34",
        "sample_name": "34",
        "metadata_1": "2018-01-08",
        "metadata_2": "toddler",
        "metadata_3": "",
        "metadata_4": "",
        "metadata_5": "",
        "metadata_6": "invalid host age; Invalid HOST_AGE_UNIT"
    },
    {
        "sample": "sample35",
        "sample_name": "35",
        "metadata_1": "2015-06-30",
        "metadata_2": "40",
        "metadata_3": "year",
        "metadata_4": "2015-06-30",
        "metadata_5": "",
        "metadata_6": "CALC_HOST_AGE and HOST_AGE are greater than 1 year different"
    },
    {
        "sample": "sample36",
        "sample_name": "36",
        "metadata_1": "2013-06-19",
        "metadata_2": "1",
        "metadata_3": "month",
        "metadata_4": "2010-06-19",
        "metadata_5": "",
        "metadata_6": "CALC_HOST_AGE and HOST_AGE are greater than 1 year different"
    }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/categorize/reorder_headers.json
[
  {
    "sample": "sample1",
    "sample_name": "A",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "Human NCBITaxon:9606",
    "metadata_5": "Homo sapiens (Human)"
  },
  {
    "sample": "sample2",
    "sample_name": "B",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "dog",
    "metadata_5": ""
  },
  {
    "sample": "sample3",
    "sample_name": "C",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "eggs",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample4",
    "sample_name": "D",
    "metadata_1": "wastewater",
    "metadata_2": "farm",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample5",
    "sample_name": "E",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample6",
    "sample_name": "F",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "dog",
    "metadata_5": "Homo sapiens (Human)"
  },
  {
    "sample": "sample7",
    "sample_name": "G",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "",
    "metadata_5": "Homo sapiens (Human)"
  },
  {
    "sample": "sample8",
    "sample_name": "H",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": "Human NCBITaxon:9606",
    "metadata_5": ""
  },
  {
    "sample": "sample9",
    "sample_name": "J",
    "metadata_1": "wastewater",
    "metadata_2": "farm",
    "metadata_3": "eggs",
    "metadata_4": "Human NCBITaxon:9606",
    "metadata_5": "Homo sapiens (Human)"
  },
  {
    "sample": "sample10",
    "sample_name": "K",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "eggs",
    "metadata_4": "dog",
    "metadata_5": ""
  },
  {
    "sample": "sample11",
    "sample_name": "L",
    "metadata_1": "",
    "metadata_2": "farm",
    "metadata_3": "eggs",
    "metadata_4": "",
    "metadata_5": ""
  },
  {
    "sample": "sample12",
    "sample_name": "M",
    "metadata_1": "wastewater",
    "metadata_2": "",
    "metadata_3": "eggs",
    "metadata_4": "",
    "metadata_5": ""
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/pnc/basic.json
[
  {
    "sample": "sample1",
    "sample_name": "basic1",
    "metadata_1": "2020-01-01",
    "metadata_2": "2020-01-02",
    "metadata_3": "2020-01-03",
    "metadata_4": "2020-01-04",
    "metadata_5": "2020-01-05",
    "metadata_6": "2020-01-06",
    "metadata_7": "10",
    "metadata_8": "year",
    "metadata_9": "2010-01-01",
    "metadata_10": "Homo sapiens (Human)",
    "metadata_11": "Human NCBITaxon:9606",
    "metadata_12": "",
    "metadata_13": "",
    "metadata_14": ""
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/pnc/commas.json
[
  {
    "sample": "sample1",
    "sample_name": "basic1",
    "metadata_1": "2020-01-01",
    "metadata_2": "2020-01-02",
    "metadata_3": "2020-01-03",
    "metadata_4": "2020-01-04",
    "metadata_5": "2020-01-05",
    "metadata_6": "2020-01-06",
    "metadata_7": "10",
    "metadata_8": "year",
    "metadata_9": "2010-01-01",
    "metadata_10": "A, B",
    "metadata_11": "C, D, E",
    "metadata_12": "",
    "metadata_13": "",
    "metadata_14": ""
  },
  {
    "sample": "sample2",
    "sample_name": "basic2",
    "metadata_1": "2020-01-01",
    "metadata_2": "2020-01-02",
    "metadata_3": "2020-01-03",
    "metadata_4": "2020-01-04",
    "metadata_5": "2020-01-05",
    "metadata_6": "2020-01-06",
    "metadata_7": "10",
    "metadata_8": "year",
    "metadata_9": "2010-01-01",
    "metadata_10": ",,,",
    "metadata_11": "",
    "metadata_12": "",
    "metadata_13": "",
    "metadata_14": ""
  },
  {
    "sample": "sample3",
    "sample_name": "basic3",
    "metadata_1": "2020-01-01",
    "metadata_2": "2020-01-02",
    "metadata_3": "2020-01-03",
    "metadata_4": "2020-01-04",
    "metadata_5": "2020-01-05",
    "metadata_6": "2020-01-06",
    "metadata_7": "10",
    "metadata_8": "year",
    "metadata_9": "2010-01-01",
    "metadata_10": "F,",
    "metadata_11": ",G",
    "metadata_12": "",
    "metadata_13": "",
    "metadata_14": ""
  },
  {
    "sample": "sample4",
    "sample_name": "basic4",
    "metadata_1": "2020-01-01",
    "metadata_2": "2020-01-02",
    "metadata_3": "2020-01-03",
    "metadata_4": "2020-01-04",
    "metadata_5": "2020-01-05",
    "metadata_6": "2020-01-06",
    "metadata_7": "10",
    "metadata_8": "year",
    "metadata_9": "2010-01-01",
    "metadata_10": "Chicken breast (skinless, boneless)",
    "metadata_11": "Chicken breast (skinless, boneless)",
    "metadata_12": "",
    "metadata_13": "",
    "metadata_14": ""
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/age_pnc/problems.json
[
  {
    "sample": "reverse_dates_under_2",
    "sample_name": "rd_1",
    "metadata_1": "2001-01-01",
    "metadata_2": "2000-01-01",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "reverse_dates_over_2",
    "sample_name": "rd_2",
    "metadata_1": "2010-01-01",
    "metadata_2": "2000-01-01",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "bad_format_1",
    "sample_name": "bf_1",
    "metadata_1": "00-01-01",
    "metadata_2": "2000-11-11",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "bad_format_2",
    "sample_name": "bf_2",
    "metadata_1": "2000-01-01",
    "metadata_2": "00-11-11",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "bad_format_3",
    "sample_name": "bf_3",
    "metadata_1": "2000/01/01",
    "metadata_2": "2000/11/11",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "bad_format_4",
    "sample_name": "bf_4",
    "metadata_1": "2000.01.01",
    "metadata_2": "2000.11.11",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "bad_format_5",
    "sample_name": "bf_5",
    "metadata_1": "2000-01-01",
    "metadata_2": "2000-11-11 23:59:59",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "wrong_order_1",
    "sample_name": "wo_1",
    "metadata_1": "2000-31-01",
    "metadata_2": "2000-01-02",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "wrong_order_2",
    "sample_name": "wo_2",
    "metadata_1": "2000-01-01",
    "metadata_2": "2000-31-02",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "negative_date_1",
    "sample_name": "nd_1",
    "metadata_1": "-2000-01-01",
    "metadata_2": "2001-01-01",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "negative_date_2",
    "sample_name": "nd_2",
    "metadata_1": "2000-01-01",
    "metadata_2": "-2001-01-01",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "missing_date_1",
    "sample_name": "md_1",
    "metadata_1": "",
    "metadata_2": "2001-01-01",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "missing_date_2",
    "sample_name": "md_2",
    "metadata_1": "2000-01-01",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "age_not_a_number_1",
    "sample_name": "age_nan_1",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "one",
    "metadata_4": "year"
  },
  {
    "sample": "age_unit_not_string_1",
    "sample_name": "au_nas_1",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "1",
    "metadata_4": "1"
  },
  {
    "sample": "age_unit_not_string_2",
    "sample_name": "au_nas_1",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "1",
    "metadata_4": "1"
  },
  {
    "sample": "age_unit_invalid_1",
    "sample_name": "aui_1",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "1",
    "metadata_4": "cat"
  },
  {
    "sample": "consolidation_error_1",
    "sample_name": "ce_1",
    "metadata_1": "2000-01-01",
    "metadata_2": "2001-01-01",
    "metadata_3": "1000",
    "metadata_4": "year"
  },
  {
    "sample": "junk_1",
    "sample_name": "j_1",
    "metadata_1": "cat",
    "metadata_2": "dog",
    "metadata_3": "fish",
    "metadata_4": "mouse"
  },
  {
    "sample": "junk_2",
    "sample_name": "j_2",
    "metadata_1": "",
    "metadata_2": "",
    "metadata_3": "",
    "metadata_4": ""
  },
  {
    "sample": "junk_3",
    "sample_name": "j_3",
    "metadata_1": "0",
    "metadata_2": "0",
    "metadata_3": "0",
    "metadata_4": "0"
  },
  {
    "sample": "junk_4",
    "sample_name": "j_4",
    "metadata_1": "0000-00-00",
    "metadata_2": "0000-00-00",
    "metadata_3": "0000-00-00",
    "metadata_4": "0000-00-00"
  },
  {
    "sample": "junk_5",
    "sample_name": "j_5",
    "metadata_1": "1",
    "metadata_2": "2",
    "metadata_3": "3",
    "metadata_4": "4"
  },
  {
    "sample": "junk_6",
    "sample_name": "j_6",
    "metadata_1": "-2000-01-01",
    "metadata_2": "-2001-01-01",
    "metadata_3": "-10",
    "metadata_4": "year"
  }
]

=== phac-nml/metadatatransformation/tests/data/samplesheets/populate/missing_metadata.json
[
  {
    "sample": "sample1",
    "sample_name": "ABC",
    "metadata_1": "",
    "metadata_2": "1.2",
    "metadata_3": "1.3",
    "metadata_4": "",
    "metadata_5": "1.5",
    "metadata_6": "1.6",
    "metadata_7": "",
    "metadata_8": ""
  },
  {
    "sample": "sample2",
    "sample_name": "",
    "metadata_1": "2.1",
    "metadata_2": "",
    "metadata_3": "2.3",
    "metadata_4": "2.4",
    "metadata_5": "",
    "metadata_6": "2.6",
    "metadata_7": "2.7",
    "metadata_8": ""
  },
  {
    "sample": "sample3",
    "sample_name": "GHI",
    "metadata_1": "3.1",
    "metadata_2": "3.2",
    "metadata_3": "",
    "metadata_4": "3.4",
    "metadata_5": "3.5",
    "metadata_6": "",
    "metadata_7": "3.7",
    "metadata_8": ""
  }
]
